import './globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Pro Profile AI - Professional Headshots Generated by AI',
	description:
		'Transform your selfies into professional headshots with AI. Get studio-quality profile pictures in minutes for LinkedIn, resumes, and more.',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
